/// Flutter icons LessonsIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  LessonsIcons
///      fonts:
///       - asset: fonts/LessonsIcons.ttf
///
///
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Iconic, Copyright (C) 2012 by P.J. Onori
///         Author:    P.J. Onori
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://somerandomdude.com/work/iconic/
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
///
import 'package:flutter/widgets.dart';

/* Дарт дает возможность использовать файл без класса и объявлять методы и переменные на уровне файла. Я добавил файл lessons_icons_file
 .dart с примером */

//todo этот класс относится к UI его в моделях быть не должно, он должен быть у тебя в той папке где у тебя UI (в данном случае это папка
// widgets). Думаю сдесь подой
class LessonsIcons {
  //todo с какой целью используешь приватный конструктор в классе где объявлены одни статические переменные? Вобщем подумай и если это не
  // нужно то убери
  LessonsIcons._();

  static const _kFontFam = 'LessonsIcons';
  //todo эта переменная везде null. Зачем она? если не используешь что-то - удаляй
  static const String? _kFontPkg = null;

  static const IconData directions_car = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData steering_wheel = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData repair = IconData(0xea7f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

//todo думаю лучше переименовать в getIconDataByName
  static IconData getIconDataFromName(String name) {
    switch (name) {
      case 'directions_car':
        {
          return LessonsIcons.directions_car;
        }
      case 'steering_wheel':
        {
          return LessonsIcons.steering_wheel;
        }
      case 'repair':
        {
          return LessonsIcons.repair;
        }
      default:
        {
          throw Exception('No such icon with name $name');
        }
    }
  }
}
